### ISSUE TITLE
Errors encountered with cluster_generator

### ISSUE THREAD

**Issue by ShuangShuang0411** [gamer-project/gamer#300]
I’m trying to generate cluster ICs using ZuHone’s `cluster_generator` for my `ClusterMerger` test problem, but I encounter errors when running `gamer_cluster_ics.py`. I’ve followed the instructions in README:

```
   --> Install cluster_generator from GitHub and run the included gamer_cluster_ics.py script
       (1) git clone https://github.com/jzuhone/cluster_generator (somewhere else probably)
       (2) cd cluster_generator
       (3) python -m pip install .
       (4) Go back to the gamer_cluster_ics.py script and run with python "gamer_cluster_ics.py"
```

The error messages are:
```
Generating particle velocities :   0%|                                                                | 0/1452536 [00:00<?, ?it/s]
ValueError: 0-th dimension must be fixed to 998 but got 1000


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projectV/shuang/production_runs/mcf_MergerFeedback7-1/gamer_cluster_ics.py", line 144, in <module>
    cg.setup_gamer_ics(ics)
  File "/home/shuang/.local/lib/python3.10/site-packages/cluster_generator/codes.py", line 103, in setup_gamer_ics
    parts = ics._generate_particles(regenerate_particles=regenerate_particles)
  File "/home/shuang/.local/lib/python3.10/site-packages/cluster_generator/ics.py", line 165, in _generate_particles
    p = m.generate_dm_particles(
  File "/home/shuang/.local/lib/python3.10/site-packages/cluster_generator/model.py", line 776, in generate_dm_particles
    return self.dm_virial.generate_particles(
  File "/home/shuang/.local/lib/python3.10/site-packages/cluster_generator/virial.py", line 188, in generate_particles
    velocity_sub = generate_velocities(
  File "cluster_generator/cython_utils.pyx", line 70, in cluster_generator.cython_utils.generate_velocities
ValueError: failed in converting 2nd argument `c' of dfitpack.splev to C/Fortran array
```

**Comment by jzuhone** [comment]
Hi @ShuangShuang0411 please upgrade scipy to try to fix this issue.

**Comment by ShuangShuang0411** [comment]
@jzuhone It works! Thanks a lot!
